### ISSUE TITLE
Error when color fixing

### ISSUE THREAD

**Issue by SLAPaper** [pkuliyi2015/sd-webui-stablesr#10]
`[StableSR] Error fixing color with default method: Given groups=3, weight of size [3, 1, 3, 3], expected input[1, 4, 2562, 1442] to have 3 channels, but got 4 channels instead`

I'm using 1.3.0-RC.
It's too late for digging in the reason, I'll add more detail afterwards.

**Comment by l3luel3l00d** [comment]
Same problem here, any solution?

**Comment by SLAPaper** [comment]
> Same problem here, any solution?

turn off img2img color correction in `Stable Diffusion` settings

**Comment by mengjoan** [comment]
I also encountered the same error as you. It worked normally before, but after the upgrade, it cannot work normally. I have been unable to solve it.

[StableSR] Error fixing color with default method: Given groups=3, weight of size [3, 1, 3, 3], expected input[1, 4, 2562, 1442] to have 3 channels, but got 4 channels instead

**Comment by mengjoan** [comment]
> > 同样有此问题，有解决办法吗？
> 
> `Stable Diffusion`在设置中关闭 img2img 色彩校正

Have you tested it and is it possible?

**Comment by mengjoan** [comment]
> > Same problem here, any solution?
> 
> turn off img2img color correction in `Stable Diffusion` settings

Have you tested it and is it possible?
