### ISSUE TITLE
求助！加载不了大模型。

### ISSUE THREAD

**Issue by lucknini** [pkuliyi2015/sd-webui-stablesr#25]
StabilityAI 官方的 Stable Diffusion V2.1 512 EMA 模型（约 5.21GB）这个大模型加载不了。
机器是4060 8g 
请问有解决方法吗？

**Comment by pkuliyi2015** [comment]
不能复现你遇到的问题。请尝试更新webui和插件

**Comment by lucknini** [comment]
已解决，谢谢

**Comment by kevinbai** [comment]
> 已解决，谢谢

遇到同样问题，请教如何解决？
