### ISSUE TITLE
The image restoration effect is not ideal

### ISSUE THREAD

**Issue by yincangshiwei** [pkuliyi2015/sd-webui-stablesr#29]
Hello, I have a picture that using stablesr to fix has not had much effect. Can you try repairing it for me?
![原图2](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/8185843/074c89dd-64f6-4f19-8927-29b1aa8a492a)

**Comment by pkuliyi2015** [comment]
We are sorry, but StableSR is not trained on such old photos. We are unlikely to support such photo restoration in the near future.
