### ISSUE TITLE
What's the relationship between this project and Tiled Diffusion & VAE?

### ISSUE THREAD

**Issue by songtianhui** [pkuliyi2015/sd-webui-stablesr#35]
I notice the readme has mentioned another project https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 and I got confused.
What is their relationship? Which contains which? Should I install both or just one of them is enough?

**Comment by pkuliyi2015** [comment]
Normally you need to install both if you want to upscale to > 2k images.
The stablesr paper relies on Mixture of diffusers to do tiled upscale. And luckily I have implemented that before they released their paper. So this is just a coincidence.

**Comment by songtianhui** [comment]
I got it. Awesome! Thanks!
