### ISSUE TITLE
 TypeError: Script.run() missing 5 required positional arguments

### ISSUE THREAD

**Issue by delcompan** [pkuliyi2015/sd-webui-stablesr#44]
TypeError: Script.run() missing 5 required positional arguments: 'model', 'scale_factor', 'pure_noise', 'color_fix', and 'save_original'

Everything else works fine with webui, except for stablesr.The models needed for stablesr have been downloaded.

**Comment by anycall** [comment]
I also encountered the same problem, environment information: version: v1.4.1    python: 3.10.9    torch: 2.0.0+cu118    xformers: 0.0.17    gradio: 3.32.0

**Comment by delcompan** [comment]
I have solved this problem. Remove all plugins and reinstall them.
