### ISSUE TITLE
Didn't work as expected; Upscale better w/ Tiled Diffusion + Tiled VAE and w/o StableSR

### ISSUE THREAD

**Issue by snakeninny** [pkuliyi2015/sd-webui-stablesr#5]
### The original image is 
![不清晰的图片](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/0e2a9952-da82-4084-9997-9db188a740ed)

### W/o StableSR
Model is ``Deliberate`` and the parameters are as follows:
![FireShot Capture 039 - Stable Diffusion - notebooksg jarvislabs ai](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/5a269970-495e-41d6-b34b-505d8fa1a10f)

Output:
![00015-606013714](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/e1317a34-3f60-4348-8a9c-65270b33aede)

### W/ StableSR
I followed your [usage tutorial](https://github.com/pkuliyi2015/sd-webui-stablesr#4-extension-usage):
![FireShot Capture 040 - Stable Diffusion - notebooksg jarvislabs ai](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/2cd0a8d3-eb1e-46a2-8a05-c9c640796de8)

Ouput:
![tmprcasf67b](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/b9b4e0a3-4bc2-4137-bd45-1b6b77aa668a)

StableSR didn't work. Did I miss anything? Thank you!

**Comment by snakeninny** [comment]
W/ VQGAN VAE:
<img width="355" alt="Screenshot 2023-05-24 at 13 19 32" src="https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/c76e0e91-70b1-4019-95d6-798555c1dd94">

Output:
![00018-1286673448](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/641869/bf9de0a7-4373-4ae6-9a99-fe779163a9aa)

**Comment by pkuliyi2015** [comment]
Hi friends, this is because when you use StableSR, you leave the scale factor = 2 and it is too small. The output is only 256*304, far less than StableSR's working range.

Just set it to 4, it works correctly.

On my side:

![image](https://github.com/pkuliyi2015/sd-webui-stablesr/assets/59076257/0b9a135b-72f9-48ea-a3b5-251dfbc6c6cd)

**Comment by snakeninny** [comment]
> you leave the scale factor = 2

Seems that StableSR scale factor is the alternative of Tiled Diffusion scale factor when are both enabled.
I have tested StableSR scale factor 4 to 6, the output was the best. 7 started to get bad turn and 16 was even worse.
Thank you!
