### ISSUE TITLE
OOM error with 8GB Vram, what's the minimum Vram needed?

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [pkuliyi2015/sd-webui-stablesr#7]
Hi, 
I'm not sure what is the minimum Vram needed to make it work, should it work with 8GB Vram?
Do I need something special to make it work with 8GB Vram?

**Comment by pkuliyi2015** [comment]
It now requires a minimum of 6GB VRAM so it should work. Please provide your OOM errors here so I may help.

Here are all possible solutions, you may try first:

1. use --xformers on startup
2. enable Tiled VAE, set encoder tile size to 1024, decoder to 128.
3. Set Latent Tile Batch Size to 1

**Comment by a-l-e-x-d-s-9** [comment]
@pkuliyi2015 
Thank you for your help.
Great work.
